[web]
client_id = "924931594615-37sd840ffcnbd300lmlskh5bpp3q62k9.apps.googleusercontent.com"
project_id = "grading-system-project"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_secret = "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"
refresh_token = "1//044ubwdzzkNVvCgYIARAAGAQSNwF-L9IrwRp1Rx-S4mdZ8qZ5IhxZvUekneSxNwHD8jetuRxfRthwJ8ZmMT14yYuNPzqVhQbKqsg"