[web]
client_id = "924931594615-ugmtivfiobg2tjji12iglm381bm520pk.apps.googleusercontent.com"
project_id = "grading-system-project"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_secret = "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"
refresh_token = "1//04_8M1mI20cvZCgYIARAAGAQSNwF-L9Irk4yCMzKm0j_kH6O8PzOO-653Om_wb260bbtFVL-U2q7fNcDvz2ZzbPYxX_b_eAy72VQ"